allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
overrides:
  flat-cache>flatted: ^3.4.2
  path-to-regexp: ^8.4.0
  tinyglobby: ^0.2.17
  mdast-util-to-hast: ^13.2.1
  brace-expansion: ^1.1.13
  postcss: ^8.5.10
  vite: ^6.4.2
  fumadocs-mdx>picomatch: ^4.0.4
  js-yaml: ^4.2.0
